### ISSUE TITLE
uploader

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#15]
اپلودر هم در بعضی موارد به  درستی عمل نمیکنه

**Comment by mehrdad2** [comment]
تا اخر پر میشه اما هیچ اتفاقی نمی افته - نه اپلود میشه نه پیغام

**Comment by mehrdad2** [comment]
![screen shot 2016-09-07 at 12 07 17 am](https://cloud.githubusercontent.com/assets/4264683/18288128/68b30570-748f-11e6-80b6-fafae65c3616.png)

**Comment by rezakho** [comment]
مشکل حجم فایل های اپلود شده بود که با تنظیمات php برطرف شد
