### ISSUE TITLE
چینش

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#2]
در مورد چینش احتمالا فقط ۲ حالت داشته باشیم چون رسپانسیو هست خیلی ۴ تایی و ۵ تایی معنی پیدا نمیکنه
این مسئله ای نداره که؟

**Comment by rezakho** [comment]
نه موردی نداره
اون یه مثال بود
نهایی که شد بگو تا در کدهای سرور هم تغییرات رو اعمال کنم
