### ISSUE TITLE
عرض تشکر

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#20]
اقا همش که نباید از ایرادات گفت 
تشکر بابت همه چیز
کلی ویژگی عالی داره مثل بنز کار میکنه که هیچ کس جز آقا رضا نمیتونه این شکلی بسازه اینا رو
ایشالا که دیگه ایشیو! نداشته  باشیم :)
در کل ممنون
![gerbera-rosa](https://cloud.githubusercontent.com/assets/4264683/18312404/d8d2b960-751e-11e6-88d0-e0fdf45f919e.jpg)

**Comment by rezakho** [comment]
شما هم خسته نباشی
