### ISSUE TITLE
حذف url

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#23]
توضیحات رو خدمتت میگم

**Comment by mehrdad2** [comment]
اقا رضا برای این یو آر ال شدیدا تاکید دارن که فقط بخوان بزنن اف تی پی - با اچ تی اکسز نمیشه درستش کرد؟
میگن اینجور هیچ کس تو اداره نمیتونه به ذهنش بسپاره

**Comment by rezakho** [comment]
ببین هر آدرسی میشه اضافه کرد
منتها با این شرط که اولش یه 
http://
داره
ولی بقیه اش میتونه هر چیزی باشه
