### ISSUE TITLE
دکمه بروز حین آپلود وجود داشته باشد

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#25]

**Comment by rezakho** [comment]
بیشتر توضیح بده
واضح نیست

**Comment by mehrdad2** [comment]
دکمه معمولی browse :)
تاکید زیادی رو این داشتن
![screen shot 2016-09-18 at 4 07 21 pm](https://cloud.githubusercontent.com/assets/4264683/18615543/856bcd18-7dbe-11e6-886c-f959e4d2bdc3.png)
![screen shot 2016-09-18 at 4 26 53 pm](https://cloud.githubusercontent.com/assets/4264683/18615544/857405f0-7dbe-11e6-80ea-6e3ca5d1c39f.png)

**Comment by rezakho** [comment]
آهان یعنی هم درگ و هم دکمه انتخاب فایل داشته باشه؟
در تاریخ ۱۸ سپتامبر ۲۰۱۶ ۴:۴۰ ب.ظ، "mehrdad" <notifications@github.com>
نوشت:

**Comment by mehrdad2** [comment]
دقیقا :)
