### ISSUE TITLE
جست و جو کماکان مشکل دارد و به درستی سرچ نمی کند

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#27]

**Comment by rezakho** [comment]
مشکلی نمیبینم من
دقیقا چه مشکلی؟
آپدیت کردی از روی گیت؟

**Comment by mehrdad2** [comment]
مثلا تو این مورد من نود رو که سرچ میکنم نمیاره - حتی تگ هم نمیاره
![screen shot 2016-09-18 at 4 34 11 pm](https://cloud.githubusercontent.com/assets/4264683/18615524/4ea4ab60-7dbe-11e6-9d07-9f81155106d9.png)
![screen shot 2016-09-18 at 4 35 32 pm](https://cloud.githubusercontent.com/assets/4264683/18615525/4eaa0b00-7dbe-11e6-8ce9-19d8be064820.png)
![screen shot 2016-09-18 at 4 35 39 pm](https://cloud.githubusercontent.com/assets/4264683/18615526/4eb18826-7dbe-11e6-9e7e-2d853aa8c8dd.png)
![screen shot 2016-09-18 at 4 36 00 pm](https://cloud.githubusercontent.com/assets/4264683/18615527/4eb79130-7dbe-11e6-806a-4d73badead0f.png)

**Comment by rezakho** [comment]
تگ که سرچی نیست
کلیکیه یعنی کلیک باید بکنی رو تگ یکی از پست ها
سرچ رو هم فقط بنویس نود بیین میاد یا نه
در تاریخ ۱۸ سپتامبر ۲۰۱۶ ۴:۳۸ ب.ظ، "mehrdad" <notifications@github.com>
نوشت:
