### ISSUE TITLE
باز نشدن سایت

### ISSUE THREAD

**Issue by mehrdad2** [ronack/fsh#3]
مرج کردم دیگه باز نمیشه
![screen shot](https://cloud.githubusercontent.com/assets/4264683/18052841/cf999fc6-6e11-11e6-8941-f7727c9e0885.png)

**Comment by rezakho** [comment]
سیک کن رو گیت هاب که بتونم ببینم

**Comment by rezakho** [comment]
چیز خاصی نیست
مال داده های الکی توی دیبی هست
برو تو دیبی همه رکورد های post رو پاک کن
